### ISSUE TITLE
When no mouse/keyboard event onIdle is not triggered

### ISSUE THREAD

**Issue by ahayden-lg** [SupremeTechnopriest/react-idle-timer#167] opened 2021-05-29 17:54 UTC
We are using react-idle-timer v. 4.6.4 to programmatically log out of our react app when the user has been idle. 
I've found that if I login with the keyboard (with my mouse not over the browser window contain our app), that the `onIdle` event never gets triggered, until I move the mouse back into the window or press a key, at which time the onIdle is triggered, assuming the the timeout has passed.
If any mouse or keyboard event has occurred after instantiating react-idle-timer, the onIdle event tiggers as expected after the configured timeout.
Though this is a small issue, I thought that you would still like to know about it :)

**Comment by SupremeTechnopriest** [comment] 2021-05-29 22:10
Could you send me your IdleTimer config?  Sounds like you might have `startOnMount` set to false.  Ideally if you can send me a codesandbox that reproduces the issue I can confirm and fix it.

**Comment by ahayden-lg** [comment] 2021-05-30 01:26
I don't have a sandbox setup but here is a couple code snippets:

```
 const DEFAULT_IDLE_TIMEOUT = 30 * 60 * 1000;
 
class IdleTimeout extends React.Component {
  timeoutValue = DEFAULT_IDLE_TIMEOUT;
  idleTimer = null;
  serverTimerId = null;
  //...
  render() {
    this.timeoutValue = this.getTimeoutValue(); // pulls a configurable timeout value

    return (
      <div>
        <IdleTimer
          ref={ref => {
            this.idleTimer = ref;
          }}
          crossTab={{
            type: 'localStorage', 
            responseTime: 200,
            emitOnAllTabs: true, 
          }}
          timeout={this.timeoutValue}
          onAction={this.onAction}
          onActive={this.onActive}
          onIdle={this.onIdle}>
        </IdleTimer>
      </div>
    );
  }
```

**Comment by dastardlychimp** [comment] 2021-06-21 22:32
@SupremeTechnopriest I am encountering the same or similar issue, although I am using the `useIdleTimer` hook. 
This also might be related to issue: #155 

I looked around in the code, and the issue seems to be that if the timeout changes, the timeout initiated by the `start` function isn't updated or reset to use the new timeout value (if the timeout is not idle), unless there is a user event that resets the timer.

https://github.com/SupremeTechnopriest/react-idle-timer/blob/114f4640e951622184af0307843c58afbed4cb73/src/useIdleTimer.js#L505-L511

For example, in the project I'm working on we have a very large default timeout, that is then updated after an api request. However, the initial timer keeps running, and isn't reset to the new timeout value.

Here is a code sandbox example of the problem: https://codesandbox.io/s/hardcore-engelbart-728o8?file=/src/App.js

**Comment by SupremeTechnopriest** [comment] 2021-06-23 19:55
Mmm I see the issue.  I should probably not check if the timer is currently idle before resetting.  That would allow you to update the timeout during an existing timer.  

Will get that patched for the next release.

**Comment by KatieKoslosky** [comment] 2021-07-23 15:11
@SupremeTechnopriest thanks for the great library!
I would definitely be interested in that patch, do you know when that next release is coming?

**Comment by SupremeTechnopriest** [comment] 2021-07-23 20:00
hi @KatieKoslosky 

I am in the middle of a big release for my day job and wont really have time until beginning of Q4.  Some time around September or October version 5 will be released.

**Closed** 2022-02-18 04:52 UTC
