### ISSUE TITLE
Continue timer operation when more than one tab is inactive.

### ISSUE THREAD

**Issue by rffensick** [SupremeTechnopriest/react-idle-timer#170] opened 2021-06-16 09:34 UTC
We noticed that the timer stops working when no tabs are active. That is, all tabs are active but the user is not on them

Why is it done there? I would like to hear the opinion of the author

It seems to me that such cases should be done as a parameter. There are many cases when you need the timer to always work.

**Comment by SupremeTechnopriest** [comment] 2021-06-16 19:28
Not sure what you are asking here.  The purpose of an Idle Timer is to detect when a user is no longer active on your page.  What is your use case?  Do you have any sample code I can look at?

**Comment by mellis481** [comment] 2021-06-23 19:19
@SupremeTechnopriest I'm not sure if this is what the author is getting at, but is react-idle-timer expected to work properly when a tab/browser is inactive?

**Comment by SupremeTechnopriest** [comment] 2021-06-23 19:53
It should work as designed when a tab or browser is inactive. Meaning that user activity will activate the timers and associated events will be emitted.  Im not sure what is being asked here.  What criteria are you using to denote an "active" tab if a user is not on them? As far as IdleTimer is concerned, if a user is not on the tab and actively interacting with it, it is considered inactive.

**Comment by sbologescu** [comment] 2021-06-28 01:50
If you are taking about the behavior in Chromium based browsers, maybe this is the reason?
https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

**Comment by SupremeTechnopriest** [comment] 2021-06-29 20:25
If thats what we are talking about I am considering moving timers to web workers where they are supported.  This will get around the throttling of the timer. Probably will implement it using https://www.npmjs.com/package/worker-timers

Im currently working on releasing a new product for my day job, but as soon as I get some free time I will add this.

**Comment by RealDrewKlayman** [comment] 2021-07-15 17:57
Is this the reason why it when I open a ton of the same tab, the timer seems to stop working?

**Comment by SupremeTechnopriest** [comment] 2021-07-15 18:09
Yeah could be related.

**Comment by SupremeTechnopriest** [comment] 2021-11-19 22:28
I've carved out some time to get v5 out over the holiday.  This is on the list of features coming.

**Comment by sbologescu** [comment] 2022-01-11 23:12
@SupremeTechnopriest , how do I get a hold of the v5 ? I would like to test the switch to web workers. thanks!

**Comment by SupremeTechnopriest** [comment] 2022-01-11 23:19
Im just working on wrapping it up.  Ill be deploying to the @next tag soon.  I will let you know when its ready.

**Comment by sbologescu** [comment] 2022-02-15 16:32
@SupremeTechnopriest , is by any chance v5 available anywhere for me to try? thank you

**Comment by SupremeTechnopriest** [comment] 2022-02-15 20:17
Pretty sure I'll be pushing the beta today. If not tomorrow. Just a small amount of documentation remaining.

**Comment by SupremeTechnopriest** [comment] 2022-02-18 04:22
Hey @rffensick, @mellis481. @RealDrewKlayman, @JWess and @sbologescu!

Thanks for your patience while I worked through this release.  It's a really big one!  I rewrote everything from scratch in typescript including the test suites and an all new documentation site.  

Finally, the version 5 beta has been released.  You can install it with `npm i react-idle-timer@next` and check out the new documentation at [https://idletimer.dev](https://idletimer.dev).  All the timers have been moved into web-workers and will continue to run regardless of the state of the browser tab.  It's very well tested, but if you wouldn't mind installing in your applications and seeing if it resolves any issues you were seeing, I would appreciate it.  

Im going to close this issue, but feel free to open another if anything arises.

**Closed by SupremeTechnopriest** 2022-02-18 04:22 UTC

**Comment by sbologescu** [comment] 2022-02-18 13:23
@SupremeTechnopriest , thank you for getting the beta out. I will pick it up and hopefully start testing it today.

**Comment by mellis481** [comment] 2022-04-11 18:04
@SupremeTechnopriest I installed 5.0.0-rc.24 and my cursory testing of the expected behavior was successful.

Is there any timeline for version 5 being released?

**Comment by SupremeTechnopriest** [comment] 2022-04-11 23:44
Hey @mellis481!

Yes there is a release planned for April 22, 2022 at 5 PM PST.  You can join the discord to be updated on releases and future beta tests!

**Comment by SupremeTechnopriest** [comment] 2022-04-23 00:32
@mellis481 v5 is released!
