### ISSUE TITLE
Continuous mouse move triggers huge CPU usage and adds a lot of event listeners

### ISSUE THREAD

**Issue by dreamerchandra** [SupremeTechnopriest/react-idle-timer#117] opened 2020-07-17 10:01 UTC
Take a look at the performance monitor in [this video](https://teleport.video/video/message/v1/fGy4EGMwce4o). 
And code `https://codesandbox.io/s/ideal-timer-cbseh?file=/src/App.js`

**Comment by SupremeTechnopriest** [comment] 2020-07-17 17:43
Thanks for the report.  I will look into this.  I have a feeling it has to do with the `stopOnIdle` option.

**Comment by SupremeTechnopriest** [comment] 2020-07-17 19:17
@dreamerchandra, What is that realtime performance monitoring extension you are using?

**Comment by SupremeTechnopriest** [comment] 2020-07-17 21:38
As far as the events leak goes, I think what you are seeing is related to this https://github.com/facebook/react/issues/12141.  I have profiled IdleTimer and the results are consistent with what is discussed here.  Can you test a production build and see if the problem persists?  In regards to the high cpu usage, that's due to the mouse event spamming the event handler method.  I was able to get it to not surpass 2% cpu by adding a throttle to it.  I will add a new option to set a throttle on the actually event handler.  The current `throttle` and `debounce` settings only throttle and debounce the `onAction` event handler.  The new option will be something like `eventHandlerThrottle`.  Only throttle is applicable to this handler, debounce would cause the page to timeout while there is user activity.  

Im hoping to have the hook API out soon, and this update will be part of that.  Please let me know if you still see the event leak in production React.

**Comment by dreamerchandra** [comment] 2020-07-18 14:24
It's actually happening in our production build... Hence I had to create an eg sandbox to double-check myself if I was right about idle timer's performance and codesand-box proves it...
I had to create a hooks implementation of idle timer myself [sandbox included here](https://codesandbox.io/s/idle-timer-hooks-ndjji) to get our project working... And the [results are good](https://teleport.video/video/message/v1/fH8f9gdfi9iA)

**Comment by SupremeTechnopriest** [comment] 2020-07-18 17:06
Hey @dreamerchandra, thanks for the additional info.  I just tested a production build with IdleTimer, and I can confirm that the events don't leak.  Are you by chance using `create-react-app` or did you roll your own?  You seem to know what you are doing, but just for posterity I will mention that you need to be sure your app is built with `NODE_ENV=production` in order for React to run in production mode.

I finished the hook implementation last night and will be testing and documenting it today.  It looks like you have a nice minimal hook, and if it suits your needs then cool cool!  You can close this issue.  If you want all the additional features of `IdleTimer`, I expect to have the hook production ready by the end of the weekend.

**Closed** 2020-07-18 19:51 UTC

**Comment by SupremeTechnopriest** [comment] 2020-07-18 22:44
Hey @dreamerchandra, Just thought I'd let you know version `4.3.0` is published to npm.  It includes the `useIdleTimer` hook and a new property `eventsThrottle` that significantly reduces cpu usage.  It defaults to `200ms`.  Thanks for pointing out that issue.  Hope you find it helpful.
