### ISSUE TITLE
Problems with getTotalActiveTime() and reset() on v5.4

### ISSUE THREAD

**Issue by d9k** [SupremeTechnopriest/react-idle-timer#272] opened 2022-07-01 08:05 UTC
### Affected Module

- `Version`: `5.4.0`

### Describe the bug

`timer.reset()` doesn't affect `timer.getTotalActiveTime()` result.

### To Reproduce

```
const timerProps = {
 debounce: 500,
 timeout: 2000,
}

const timer = useIdleTimer(timerProps);

// after some time active

const T1 = timer.getTotalActiveTime();

timer.reset();

// then immediately after

const T2 = timer.getTotalActiveTime();
```

### Expected behavior

`T2` should be `0`. But it's `T1`.

### System Information (please complete the following information)

 - `OS`: Ubuntu 18.04
 - `Device`: Desktop
 - `Browser Vendor`: Chrome
 - `Browser Version`: 102.0.5005.61
 
### Additional context

See previous issue about `getTotalActiveTime()` and `reset`: https://github.com/SupremeTechnopriest/react-idle-timer/issues/257

**Comment by SupremeTechnopriest** [comment] 2022-07-01 19:16
This was actually by design, but after the recent changes to `reset` I think your suggestion should be implemented.  I will get this out in the next release.

**Comment by SupremeTechnopriest** [comment] 2022-07-06 17:04
@d9k, This is resolved in `5.4.1`.  I added a test for this case so you should be good to go, but feel free to re open if you are still having issues.

**Closed by SupremeTechnopriest** 2022-07-06 17:04 UTC
Labels: bug

**Comment by d9k** [comment] 2022-10-28 06:02
I tried to update my code. With `5.4.2` after `reset()` time doesn't go "below zero", but actually there is a delay before `getTotalActiveTime()` gets > 0 again. So strange...

**Comment by d9k** [comment] 2022-10-28 06:14
1) Can't debug compiled react-idle-timer with storybook in my project because when I try to pretty print oneliner in Chrome dev tools it's empty
2) Tried to include react-idle-timer to the code of my project to debug how it works with my code but got so many compile errors...

![Screenshot from 2022-10-28 09-10-57](https://user-images.githubusercontent.com/7331988/198516298-8f6d43ea-50ab-4887-bb68-08da7ff33234.png)

**Comment by d9k** [comment] 2022-10-28 06:42
@SupremeTechnopriest, how can I rebuild react-idle-timer 5.4.2 (index.esm.js) locally without minification?
