### ISSUE TITLE
CPU sleep and getLastActiveTime

### ISSUE THREAD

**Issue by brianjutrzonka** [SupremeTechnopriest/react-idle-timer#290] opened 2022-10-19 16:24 UTC
## Bug information
I am having an issue that relates to putting my CPU to sleep and then coming back to the idle timer. Basically, I am trying to compare dates from the current time to the getLastActiveTime time that react-idle-timer provides.  If the user is over the timeouts that I set, I want to log the user out.

However, when I put my computer to sleep for a minute or so, and then come back to the timer, it seems as though the getLastActiveTime value is at least a couple of minutes behind the current time. 

### Affected Module

- `Version`: 5.4.2

### To Reproduce

1. Open a browser with the idle timer running.
2. Set the timeout to a larger number and have a way to log the getLastActiveTime.
3. Put your computer to sleep for a minute or two.
4. Go back to the idle timer and log out the getLastActiveTime

### Expected behavior

After your computer goes to sleep and you come back to the idle timer, after a user completes an action, the getLastActiveTime should be up to the current date the user did the action

**Comment by SupremeTechnopriest** [comment] 2022-10-20 20:33
Duplicate of #281.  A fix for this is in the works.

**Closed by SupremeTechnopriest** 2022-10-20 20:33 UTC
Labels: duplicate

**Comment by brianjutrzonka** [comment] 2022-10-24 16:16
@SupremeTechnopriest - OK great, thanks!  I will check back over the next couple of weeks to see if anything has been fixed
