### ISSUE TITLE
Web Worker Timers is not working as expected.

### ISSUE THREAD

**Issue by nenjamin2405** [SupremeTechnopriest/react-idle-timer#247] opened 2022-04-28 04:30 UTC
### Affected Module

- `Version`: 5.0.0

### Describe the bug

I followed the [Integrated Prompting](https://idletimer.dev/docs/getting-started/new#integrated-prompting) example, and already applied the [Web Worker Timers](https://idletimer.dev/docs/getting-started/new#web-worker-timers). It works well when I have only a few tabs, however, when I open multiple tabs (11 or more), the timer starts to be frozen and doesn't count down. In some cases during my test, it still counts down when I opened 11 or more, but most of the time it will be frozen.

### To Reproduce

Please check my [codesandbox](https://codesandbox.io/s/trusting-galois-gum2vy?file=/src/App.js) and my youtube's unlisted [video](https://youtu.be/eI890mqryng) here to see my steps to reproduce the bug. 

### Expected behavior

The timer should count down and sync across tabs regardless of the number of tabs.

### Screenshots

Please check my youtube's unlisted [video](https://youtu.be/eI890mqryng) here to see my steps to reproduce the bug. 

### System Information (please complete the following information)

 - `OS`: macOS Monterey 12.3.1
 - `Device`: Macbook
 - `Browser Vendor`: Google Chrome
 - `Browser Version`: Version 100.0.4896.127 (Official Build) (x86_64)

**Comment by SupremeTechnopriest** [comment] 2022-04-28 04:34
Thanks for the report.  I will look into this.  Out of curiosity, does it happen when you use the native timers?  (Omit the `workerTimers` prop.  That would help me in narrowing down the issue.

**Comment by nenjamin2405** [comment] 2022-04-28 04:42
Hi @SupremeTechnopriest, thank you for looking into this. The answer is `yes`, it still happens when I use the native timers. Previously I used native timers and saw this issue, that's why I checked stackoverflow and saw this related [bug](https://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome), people suggested to use WebWorker, then I found out in `react-idle-timer` you support the `Web Worker Timers` so I tried to apply it but it doesn't resolve the problem.

**Comment by SupremeTechnopriest** [comment] 2022-04-28 05:06
So I had another async middleware that was calling `next`. Pulled that out and I stopped getting the error, but the main issue is still persisting (the hanging on the second call).  I create a very minimal test file to make sure its not related to my code:

```js
const { Server } = require('hyper-express')

const app = new Server()

app.get('/', (_, res) => {
  res.status(200).send('Hello World')
})

app.post(
  '/echo',
  async (req) => {
    req.body = await req.json()
    return
  },
  (req, res, next) => {
    res.locals.data = req.body
    next()
  },
  (_, res) => {
    res.status(200).json(res.locals.data)
  }
)

app.listen(3000).then(() => {
  console.log('Listening')
})```

The get method is throwing this error and crashing the server:

```
/node_modules/hyper-express/src/components/http/Request.js:93
        this.#raw_response.pause();
                           ^

Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at Request.pause (/Users/rl/Sites/projects/edgemesh/v4/core-api/node_modules/hyper-express/src/components/http/Request.js:93:28)
    at /Users/rl/Sites/projects/edgemesh/v4/core-api/node_modules/hyper-express/src/components/http/Request.js:160:46
```

The post method with the request body `{ "foo": "bar" }` echos back the body on the first call and then hangs on the second.  If I cancel the second call and submit a third, it returns.  Then it hangs... and so on. 

Could you run this file locally and test the routes with postman and confirm you get the same results?

**Comment by SupremeTechnopriest** [comment] 2022-04-28 05:43
Sorry that was for another issue...

**Comment by SupremeTechnopriest** [comment] 2022-04-28 06:01
Are you by chance using the `syncTimers` option?  Maybe you could drop your instantiation code here on the issue so I will have a good idea of where to look for issues.

**Comment by nenjamin2405** [comment] 2022-04-28 06:50
@SupremeTechnopriest Yes, my project requires me to deal with high number of tabs, it requires the high security for the data, so no matter how many tabs I open, after the user is inactive for 20 minutes for example, it should log the user out. But because of this bug I cannot guarantee that requirement. Here is the [codesandbox](https://codesandbox.io/s/trusting-galois-gum2vy?file=/src/App.js) for the example that I showed you in the youtube video.

**Comment by SupremeTechnopriest** [comment] 2022-04-28 06:59
I understand. Could you try one more thing for me. Try disabling syncTimers and see if the issue still occurs. I will carve out some time on Saturday to solve this for you.

**Comment by SupremeTechnopriest** [comment] 2022-04-28 17:59
Hey @nenjamin2405,

One last thing for you to try.  Can you try to disable the `syncTimers` prop?  I will get into this this weekend.

**Comment by nenjamin2405** [comment] 2022-04-29 02:50
@SupremeTechnopriest I just tested again by removing `syncTimers`, the issue still occurs. When the issue occurs, as soon as I remove some of the tabs (4-5 tabs), the status of the timer will be changed from frozen to running.

**Comment by SupremeTechnopriest** [comment] 2022-04-29 02:54
Alright thank you for the info.  I will look into this this weekend.  We might be hitting the limits of web workers in the browser, but I will dig in and confirm.  The only two things that could be at play here are `BroadcastChannel` or `WebWorkers`.  Have you tried on any other platforms or devices?  Or maybe you could grab a snapshot from Activity Monitor for me?

**Comment by nenjamin2405** [comment] 2022-04-29 03:43
@SupremeTechnopriest Sometimes even I opened 14 or 15 tabs, the timer is still running, but most of the time it's frozen, so I'm not sure is it related to the limits of web workers in the browser or not. I tested this issue on my iPhone and it occurs.

**Comment by SupremeTechnopriest** [comment] 2022-04-29 03:49
Alright... I cant imagine what could be the cause of this other than a limit on web workers. The react code itself should have no issues with many tabs.  Ill get into this weekend and at least get you a root cause, if not a solution.

**Comment by SupremeTechnopriest** [comment] 2022-04-30 05:55
So I just updated to chrome v100 and man something is up with this release.  It's crushing my cpu with my usual tab load. without running any IdleTimer instances. Could you test in a different browser like Safari or Firefox? Im pretty sure this is an issue with the latest release of chrome:

<img width="965" alt="Screen Shot 2022-04-29 at 10 53 12 PM" src="https://user-images.githubusercontent.com/2261598/166093444-4ee62484-7299-4512-82a3-a53ff1f5522b.png">

The top three processes are chrome using over 300% of my CPU.  Im not running any IdleTimer instances but I have over 11 tabs open.  I can't see a reason why this issue would be related to Idle Timer....

**Comment by mCzolko** [comment] 2022-05-02 10:14
Hi, I'm having same problem as @nenjamin2405 has. Our setup is:

```js
useIdleTimer({
  crossTab: true,
  timeout: 1000 * Number(config.AUTOMATIC_LOGOUT),
  onIdle: () => dispatchEvent('logout'),
  onAction: () => dispatchEvent('user-active'),
})
```

With 5 and more windows the chrome tabs started to crash.
We had to remove idle timer from production and it resolved the problem.

Thank you for this library @SupremeTechnopriest and @nenjamin2405 for amazing job (codesandbox and youtube) reproducing the issue but we have to get to the bottom of this.

I've tried to reproduce the issue in codesandbox with Chrome v101 and it was working fine. @nenjamin2405 could you please confirm that maybe only the Chrome v100 is buggy?

**Comment by nenjamin2405** [comment] 2022-05-02 11:16
Hi @SupremeTechnopriest @mCzolko, I tested again on Firefox, the same issue happens, so I don't think it's related to Chrome only. 

I also faced another weird issue related to the inconsistency of timers across tabs, some of the tabs didn't show the timer, and you can see both of the issues in these 2 videos I list below. Sometimes I can see that when I open a lot of tabs and the timer is frozen, my macbook starts to have a heavy noise (indicates that the CPU is running heavily to compute I think)

https://youtu.be/-CXqvcb6Ii0
https://youtu.be/iHzxbruL93U

**Comment by SupremeTechnopriest** [comment] 2022-05-02 17:47
@nenjamin2405 @mCzolko,

Interesting... I will bust out the profiler and try to figure out why this happens.

**Comment by mCzolko** [comment] 2022-05-02 18:56
@SupremeTechnopriest Thanks, is there any way how to profile it correctly so I can provide you with data. I'd like to help

**Comment by SupremeTechnopriest** [comment] 2022-05-02 23:36
@mCzolko I will get to it tonight after work, but I was going to just use the chrome dev tools.  I tend to doubt that this is related to the idle timer code itself. So I'm going to try to profile the web workers and the broadcast channel.  What would be helpful is a screenshot of your activity monitor while the error is present.

**Comment by mCzolko** [comment] 2022-05-06 07:25
any luck?

**Comment by SupremeTechnopriest** [comment] 2022-05-09 03:07
Sorry @mCzolko I ended up getting really busy.  Im going to play around with this tonight and I will get back to you.

**Comment by mCzolko** [comment] 2022-05-24 11:49
well...

**Comment by dstanich** [comment] 2022-06-09 02:55
@SupremeTechnopriest I ran into this problem today while trying out the package.  Similar behavior to what was reported above where I would get over a certain number of tabs then CPU would spike and idle timeouts became unpredictable.  I did notice that closing the last tab I opened typically fixed the problem.

When the CPU was spiking I did a profile and it seemed to be doing _many_ calls to the [message handler here](https://github.com/SupremeTechnopriest/react-idle-timer/blob/eae73baf1a8d1a91e30d4404666cb81e9cecf9e1/src/TabManager/index.ts#L57).  I edited the code locally to `console.log()` the message and it would repeat the `ACTIVE` action over and over in an infinite loop.

I believe the problem may be with [how the tokens are generated](https://github.com/SupremeTechnopriest/react-idle-timer/blob/eae73baf1a8d1a91e30d4404666cb81e9cecf9e1/src/utils/token.ts#L9). If you open enough tabs eventually you end up with two tabs that have the same token.  Sometimes I see this as low as 7 tabs or as high as 12.  When the message handler tries to handle the incoming message and does checks [like this one](https://github.com/SupremeTechnopriest/react-idle-timer/blob/eae73baf1a8d1a91e30d4404666cb81e9cecf9e1/src/TabManager/index.ts#L133-L135) it triggers an infinite message loop between the two tabs with the same token.  Closing one of the tabs makes the loop stop.

If I change the code locally to use a different mechanism to create tokens (something like `Math.random() * 99999`, as a quick test) then I no longer see the problem even with 15+ tabs open.

Hopefully this is the same root cause that others are reporting.  I'd be happy to test out any other scenarios or fix if that is helpful.

**Comment by SupremeTechnopriest** [comment] 2022-06-09 03:11
@dstanich thats some damn fine debugging sir. I will push a patch tonight and see if it helps. Will keep you posted.

**Comment by SupremeTechnopriest** [comment] 2022-06-10 03:53
Sorry for the delay on this one and thanks again to @dstanich for your detailed debugging.  The profile definitely pointed me in the right direction.  Turns out the token was only half the problem.  The other half was an event leak that could get pretty nasty in certain edge cases.  I changed the token generation to use `Math.random` so we should not have any collisions in the future.  I added a test that simulates 100 tabs and makes sure there are no collisions.

If you could give `5.4.0` a test and let me know if that resolves the issue for you I would appreciate it.  If you are able to recreate the issue on the new version, please reopen this issue.

**Closed by SupremeTechnopriest** 2022-06-10 03:53 UTC
Labels: bug

**Comment by SupremeTechnopriest** [comment] 2022-06-10 03:56
I also added a method to get the tab id (token) just in case its needed in the future. It could also be used to identify unique tabs in your own code.  It only added a few lines and thought it would be a good addition. 

https://idletimer.dev/docs/api/methods#gettabid

**Comment by dstanich** [comment] 2022-06-10 11:56
Thank you for the bug fixes!!

I tried it out and no longer see the issues I saw before so I believe the fix works.  I'll keep an eye on it as we continue to add it to our application.

**Comment by SupremeTechnopriest** [comment] 2022-06-10 18:09
@nenjamin2405 & @mCzolko Just making sure you saw this.  You are good to go with `5.4.0`
