### ISSUE TITLE
Events not being executed on function component

### ISSUE THREAD

**Issue by MarianoVeloso** [SupremeTechnopriest/react-idle-timer#325] opened 2023-02-01 17:14 UTC
## Bug information

Hi! I have seted up my handler for the idle, so:

```

export default function UserHandleSession () {
	const { instance } = useMsal();
	const [open, setOpenModal] = useState(false);
	const [counter, setCounter] = useState(0);
  
	useEffect(() => {
		if(open)
			counter > 0 && setTimeout(() => setCounter(counter - 1), 1000);
	}, [counter]);

	const modalMsg = `You will be logged out in ${counter} seconds. Do you want to stay signed in?`;

	const onIdle = () => {
		console.log('onIdle');
		signOutUser();
	};

	const onPrompt = () => {
		console.log('onPrompt');
		setCounter(60);
		setOpenModal(true);
	};
	
	useIdleTimer({ onIdle, onPrompt, promptTimeout: 10000, 
		timeout: 2000,
		startOnMount: true,
		events:[
			'mousewheel',
			'mousedown',
			'touchstart',
			'touchmove',
		] });
	
	const signOutUser = () => {
		setOpenModal(true);
		SignOutUser(instance);
	};

	const handleOnConfirm = () => {
		console.log('executed confirm');
		setOpenModal(false);
	};

	return(
		<CustomDialog
			content={modalMsg}
			title={'Your session is about to expire'}
			open={open}
			cancelText={'Log Out'}
			confirmText={'Yes'}
			handleOnConfirm={handleOnConfirm}
			handleClose={signOutUser}
		/>
	);
}

```
and then in my App.tsx

```
				<div className="App">
				        <UserHandleSession/>
				        <Routes>
					        //The rest of the app
				        </Routes>	
				</div>
```

The problem is that it excecutes my modal at 2 seconds as it's expected but i'm not able to get it again and in the next minute it executes "onIdle" event, no matters if I click on the screen. I try to add all the events but the issue remains the same, is not detecting the events.

   ```
 "react": "^18.2.0",
    "react-idle-timer": "^5.4.2",
```

**Comment by SupremeTechnopriest** [comment] 2023-02-01 17:56
So this is by design.  When the user is in the prompt state activity wont reset the timer automatically.  This is so you can give your user the ability to interact with your prompt. Without it disappearing when you move your mouse.  I personally don't think that elements unexpectedly popping off the page is good UX,  but you are able to achieve this if that is what you want to do utilizing the `onAction` handler.

```ts
function onAction () {
  if (isPrompted()) activate()
}

const { isPrompted, activate } = useIdleTimer({ onAction, throttle: 200, ... })
```

I would apply a `throttle` or `debounce` as well so you aren't getting hammered by events.

**Comment by SupremeTechnopriest** [comment] 2023-02-01 17:57
Feel free to close this if it answers your question!

**Comment by MarianoVeloso** [comment] 2023-02-01 18:45
Hi! @SupremeTechnopriest. The behaviour that i'm specting is that if onPrompt is activated, with I close my modal the events starts firing again. That is not what i'm seeing at the moment, it fires the first time and in the second time nothing else happens. I'm using this to expand user session, so I expect to popups again un 15 minutes (my real case)

**Comment by MarianoVeloso** [comment] 2023-02-01 19:12
This actually works for me, but i'm not sure if i'm following the patterns of the library. Can you guide me?

```
	useEffect(() => {
		if(open){
			counter > 0 && setTimeout(() => setCounter(counter - 1), 1000);
			if(counter > 60) signOutUser();
		}
	}, [counter]);

	const onIdle = () => {
		setCounter(60);
		setOpenModal(true);
	};
		
	useIdleTimer({ onIdle, 
		timeout: 900000, //Fifteen minutes,
		throttle: 900000, //Fifteen minutes,
		events:[
			'mousewheel',
			'mousedown',
			'touchstart',
			'touchmove',
		] });
	
```

**Closed** 2023-02-01 19:15 UTC
Labels: question, triage
